services:
  alpes-sistema:
    build: .
    container_name: alpes-sistema
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - PORT=8501
      - ENVIRONMENT=production
